name: youtube_bg_player
description: A Flutter YouTube Player with background playback.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.2.0
  better_player: ^0.0.83 # Поддерживает фоновый режим из коробки
  cue_sheet: ^1.2.0