name: Flutter Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    # Полный патч для плагина flutter_inappwebview
    - name: Patch flutter_inappwebview Gradle Issues
      run: |
        WEBVIEW_BUILD_GRADLE="/home/runner/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/android/build.gradle"
        
        # 1. Исправляем старую ошибку Proguard
        sed -i "s/proguard-android.txt/proguard-android-optimize.txt/g" "$WEBVIEW_BUILD_GRADLE"
        
        # 2. Внедряем обязательный namespace сразу после строки 'android {'
        sed -i '/android {/a \    namespace "com.pichillilorenzo.flutter_inappwebview"' "$WEBVIEW_BUILD_GRADLE"
        
        echo "Патчи для flutter_inappwebview успешно применены!"

    - name: Build APK
      run: flutter build apk --debug --android-skip-build-dependency-validation
      env:
        _JAVA_OPTIONS: "-Xmx4g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.workers.max=2"