name: Flutter Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    # Тотальная очистка старого кэша сборки
    - name: Pre-build Clean
      run: |
        flutter clean
        flutter pub get

    # Точечный патч для исправления ошибки Proguard в кэше плагина WebView
    - name: Patch flutter_inappwebview Proguard Error
      run: |
        WEBVIEW_BUILD_GRADLE="/home/runner/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/android/build.gradle"
        if [ -f "$WEBVIEW_BUILD_GRADLE" ]; then
          sed -i "s/proguard-android.txt/proguard-android-optimize.txt/g" "$WEBVIEW_BUILD_GRADLE"
          echo "Патч Proguard успешно применен!"
        fi

    - name: Build APK
      run: flutter build apk --debug
      env:
        _JAVA_OPTIONS: "-Xmx4g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.workers.max=2"