name: Flutter Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    # ВОТ ОН — НАШ СВЕРХНАДЕЖНЫЙ СПАСИТЕЛЬНЫЙ ХАК:
    - name: Patch flutter_inappwebview Proguard Error
      run: |
        # Находим файл build.gradle проблемного плагина в кэше pub.dev и заменяем устаревший файл на правильный
        sed -i "s/proguard-android.txt/proguard-android-optimize.txt/g" /home/runner/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/android/build.gradle

    - name: Build APK
      run: flutter build apk --debug --android-skip-build-dependency-validation