name: Build Android APK

on:
  push:
    branches:
      - main # Сборка запустится при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest # Операционная система указывается здесь один раз

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-bg-player-apk
          path: build/app/outputs/flutter-apk/app-release.apk